### ISSUE TITLE
cann't download for chrome

### ISSUE THREAD

**Issue by tuchao1996** [pd4d10/octohint#38] opened 2021-10-26 17:56 UTC
cann't download for chrome

**Comment by anis105** [comment] 2021-12-01 06:07
met the same issue.

**Comment by zhuangyin8** [comment] 2021-12-03 01:58
met the same issue.

**Comment by lewisje** [comment] 2021-12-27 05:15
This is a duplicate of #37

**Comment by pd4d10** [comment] 2022-02-03 04:58
Duplicate of #37 , let's track it there.

**Closed as completed by pd4d10** 2022-02-03 04:58 UTC
